spring.application.name=Warmify

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/warmify
spring.datasource.username=postgres
spring.datasource.password=161003

api.security.token.secret=${JWT_SECRET:my-secret-key}
server.address=0.0.0.0

spring.jpa.open-in-view=false
