CREATE TABLE users(
    id UUID PRIMARY KEY UNIQUE DEFAULT GEN_RANDOM_UUID(),
    active BOOLEAN DEFAULT TRUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);