CREATE TABLE instagram(
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    google_authenticator_email VARCHAR(255) NOT NULL,
    status VARCHAR(50),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);