CREATE TABLE domains(
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    dom_url VARCHAR(100) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);