CREATE TABLE domains(
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    dom_url VARCHAR(100),

    created_at TIMESTAMP WITH TIME ZONE CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE CURRENT_TIMESTAMP
);