CREATE TABLE business_portfolio(
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    bm_name VARCHAR(255) NOT NULL,
    dom VARCHAR(255) NOT NULL UNIQUE,
    cnjp VARCHAR(255) NOT NULL,
    cnpj_pdf VARCHAR(255)
    status VARCHAR(50) NOT NULL,
    dom_id UUID NOT NULL,

    CONSTRAINT fk_dom FOREIGN KEY (dom_id) REFERENCES domains(id),

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);